import {
  faArrowRight,
  faBriefcase,
  faCalendarDays,
  faCalendarWeek,
  faCarSide,
  faChartSimple,
  faCheck,
  faCircleHalfStroke,
  faClipboardCheck,
  faClipboardList,
  faCreditCard,
  faFaceFrown,
  faFaceMeh,
  faFaceSmile,
  faFileArrowUp,
  faFilePdf,
  faFilter,
  faFont,
  faHeart,
  faHouse,
  faHouseChimney,
  faKeyboard,
  faMagnifyingGlass,
  faPlus,
  faPrint,
  faQuestion,
  faReceipt,
  faRightFromBracket,
  faRightToBracket,
  faRotate,
  faShieldHalved,
  faTaxi,
  faThumbsDown,
  faThumbsUp,
  faTriangleExclamation,
  faUser,
  faUsers,
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const fontAwesomeIcons = {
  add: faPlus,
  arrowRight: faArrowRight,
  briefcase: faBriefcase,
  calendar: faCalendarWeek,
  calendarDay: faCalendarDays,
  car: faCarSide,
  check: faCheck,
  checklist: faClipboardCheck,
  clipboardList: faClipboardList,
  contrast: faCircleHalfStroke,
  dashboard: faHouse,
  exportFile: faFileArrowUp,
  pdf: faFilePdf,
  filter: faFilter,
  font: faFont,
  frown: faFaceFrown,
  heart: faHeart,
  home: faHouseChimney,
  keyboard: faKeyboard,
  meh: faFaceMeh,
  payment: faCreditCard,
  print: faPrint,
  question: faQuestion,
  receipt: faReceipt,
  report: faChartSimple,
  resident: faUser,
  login: faRightToBracket,
  logout: faRightFromBracket,
  rotate: faRotate,
  search: faMagnifyingGlass,
  admin: faShieldHalved,
  smile: faFaceSmile,
  taxi: faTaxi,
  thumbsDown: faThumbsDown,
  thumbsUp: faThumbsUp,
  warning: faTriangleExclamation,
  users: faUsers,
} as const satisfies Record<string, IconDefinition>;

export type FontAwesomeIconName = keyof typeof fontAwesomeIcons;
